language: node_js
node_js:
- 12
env:
  global:
    GITHUB_TOKEN: Va8uC54DdPB+9eX39jzt2l9eXVBikB9nmymUJbCHV46DAhPUcqFovSmMDwWbor249iA4fvDGfcEwK2cxAVrgCSO2DxrQ4HwjeWUmIgcd8ckW+U5THnITXsSyAugN2iYVltzQgGcJPzq4mIV4wtsXMqX3h4oDw07x9u8XLBXYiEoFVYYt9OfExWyP430YsP4jk0YnnExmwx4X2lIVcT0qepfk+rK4r5//qVFB4EgndWdhO42ea45da32FFqGQnvcNc5uoUSX0YbL2VSH1kp8KDINevlfHNg2IRigso/9yphWA2vmJfJIxMO4b2cKZXVNqVccUQuuyWZQi+jTHcOgbQtVhRjGupfGisOpNX8QF414EAebvJ+SHQXyrAV5tBluktIRsFfbkiPiqeiYK0MczDBO7S5i3lfhm4z6JwdIeZ4+WtmGOdrSOe+BCzS91YOtwCYkHv7aZQ/8RGEVe3xtZSKFBL/o4X8cv2BG5u8X1+OajLb/QxbI94szxCzyb87gu9hk7j5bmdeWxqqDOynQJ0yxgb1/U0c1lit3CvX33sWx5yTk1lsC+tFNDCCoD+iNh6/lJTpNJxW3Sv7Mca6fJVQP2dSlWjAjWw7Oh3Ug1vHyRDbhhlcqOYfisI12KSrCcijPhpEa4Qsvdb+aZ2K7BzCW7/43phBOEuIZDvjhJMUs=
install: npm install
script: npm start
